# Import Numpy

In [36]:
import numpy as np

# Creating NumPy arrays
There are many ways to create arrays in NumPy. 

In [37]:
data = np.array([1, 2, 3, 4, 5])   # Create a rank 1 array

In [38]:
print(data)

[1 2 3 4 5]


In [39]:
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [40]:
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [41]:
random=np.random.random(5)
print(random)

[0.46352186 0.90741472 0.95540548 0.1678829  0.86366359]


# Array Arithmetic Operations

In [42]:
addition = data + ones 
print(addition)

[2. 3. 4. 5. 6.]


In [43]:
multiplication= data*zeros
print (multiplication)

[0. 0. 0. 0. 0.]


# Indexing & Slicing

In [44]:
i1=data[0]
print(i1)

1


In [45]:
i=2
i2=data[i]
print(i2)

3


In [46]:
slice=data[2:3]  #this slice looks similar to indexed value. But slice is an array whereas index is about values
print(slice)

[3]


In [47]:
slice1=data[0:2]
print(slice1)

[1 2]


In [48]:
slice2=data[1:]
print(slice2)

[2 3 4 5]


In [49]:
slice2=data[:5]
print(slice2)

[1 2 3 4 5]


# Aggregation

In [50]:
print(data.max())
print(data.min())
print(data.sum())

5
1
15


# Exercise

Create an array of length 8. Create two slices - one with first 4 elements and another with last 4 elements. Add the two slices and print the result.

In [51]:
import numpy as np


In [52]:
data = np.array([1,2,3,4,5,6,7,8])
d1 = data[:4]
d2 = data[4:]


In [53]:
print (d1)

[1 2 3 4]


In [54]:
print(d2)

[5 6 7 8]


In [55]:
print(np.add(d1,d2))

[ 6  8 10 12]


In [56]:
np.concatenate((d1,d2),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
np.concatenate((d1,d2),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])